apiVersion: apps/v1
kind: Deployment
metadata:
  name: myplanet
spec:
  selector:
    matchLabels:
      app: myplanet
  template:
    metadata:
      labels:
        app: myplanet
    spec:
      containers:
      - name: myplanet
        image: IMAGE_URL/myplanet:latest
        ports:
        - containerPort: 80
        resources:
            limits:
              cpu: "250m"
              memory: "1Gi"
            requests:
              cpu: "100m"
              memory: "256Mi"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: myplanet-service-svc
spec:
  type: LoadBalancer
  selector:
    app: myplanet
  ports:
  - port: 80
        